import os, io, sys
import pandas as pd
from google.cloud import vision
from googletrans import Translator

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)


os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = resource_path("resources/ServiceAccountToken.json")

client = vision.ImageAnnotatorClient()
translator = Translator()

def langDetection():
    with io.open(resource_path("resources/image.png"), 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)

    response = client.text_detection(image=image)
    df = pd.DataFrame(columns=['locale', 'description'])

    texts = response.text_annotations
    for text in texts:
        df = df.append(
            dict(
                locale=text.locale,
                description=text.description
            ),
            ignore_index=True
        )

    if (df['description'].any()):
        extractedString = df['description'][0]
        print(extractedString)
        return iso_639.get(translator.detect(extractedString).lang)
    else:
        return "No Result"
    
iso_639 = {'ab': 'Abkhazia (Abkhaz)',
    'aa': 'Djibouti, Eritrea, Ethiopia (Afar)',
    'af': 'South Africa, Namibia (Afrikaans)',
    'ak': 'Ghana (Akan)',
    'sq': 'Albania (Albanian)',
    'am': 'Ethiopia (Amharic)',
    'ar': 'Egypt, Jordan, Qatar, Tunisia, UAE, (Arabic)',
    'an': 'Spain (Aragonese)',
    'hy': 'Armenia (Armenian)',
    'as': 'India (Assamese)',
    'av': 'Russia, Azerbaijan, Kazakhstan, Georgia (Avaric)',
    'ae': 'Iran (Avestan)',
    'ay': 'Bolivia (Aymara)',
    'az': 'Azerbaijan (Azerbaijani)',
    'bm': 'Mali (Bambara)',
    'ba': 'Russia (Bashkir)',
    'eu': 'Spain (Basque)',
    'be': 'Belarus (Belarusian)',
    'bn': 'Bangladesh (Bengali)',
    'bh': 'India, Nepal (Bihari)',
    'bi': 'Vanuatu (Bislama)',
    'bs': 'Bosnia (Bosnian)',
    'br': 'France (Breton)',
    'bg': 'Bulgaria (Bulgarian)',
    'my': 'Burma (Burmese)',
    'ca': 'Spain, Andorra, France, Italy (Catalan/Valencian)',
    'ch': 'Mariana Islands (Chamorro)',
    'ce': 'Russia (Chechen)',
    'ny': 'Malawi (Chichewa/Nyanja)',
    'zh': 'China (Chinese)',
    'cv': 'Russia (Chuvash)',
    'kw': 'UK (Cornish)',
    'co': 'France, Italy (Corsican)',
    'cr': 'Canada (Cree)',
    'hr': 'Croatia (Croatian)',
    'cs': 'Czech Republic (Czech)',
    'da': 'Denmark (Danish)',
    'dv': 'Maldives (Divehi/Maldivian)',
    'nl': 'Netherlands (Dutch)',
    'dz': 'Bhutan (Dzongkha)',
    'en': 'English',
    'eo': 'International (Esperanto)',
    'et': 'Estonia (Estonian)',
    'ee': 'Ghana (Ewe)',
    'fo': 'Denmark (Faroese)',
    'fj': 'Fiji (Fijian)',
    'fi': 'Finland (Finnish)',
    'fr': 'France, Belgium, Luxembourg, Canada, Madagascar, Senegal, Switzerland, Vanuatu (French)',
    'ff': 'Burkina Faso (Fula)',
    'gl': 'Italy (Galician)',
    'ka': 'Georgia (Georgian)',
    'de': 'Germany, Austria, Belgium, Switzerland, Luxembourg (German)',
    'el': 'Greece (Greek)',
    'gn': 'Argentina (Guaraní)',
    'gu': 'India (Gujarati)',
    'ht': 'Haiti (Haitian)',
    'ha': 'Niger (Hausa)',
    'he': 'Israel (Hebrew)',
    'hz': 'Niger (Herero)',
    'hi': 'India (Hindi)',
    'ho': 'Papua New Guinea (Hiri Motu)',
    'hu': 'Hungary (Hungarian)',
    'ia': 'International (Interlingua)',
    'id': 'Indonesia (Indonesian)',
    'ie': 'International (Interlingue)',
    'ga': 'Ireland (Irish)',
    'ig': 'Nigeria (Igbo)',
    'ik': 'USA - Alaska (Inupiaq)',
    'io': 'International (Ido)',
    'is': 'Iceland (Icelandic)',
    'it': 'Italy (Italian)',
    'iu': 'Canada (Inuktitut)',
    'ja': 'Japan (Japanese)',
    'jv': 'Indonesia (Javanese)',
    'kl': 'Greenland (Kalaallisut)',
    'kn': 'India (Kannada)',
    'kr': 'Niger (Kanuri)',
    'ks': 'India (Kashmiri)',
    'kk': 'Kazakhstan (Kazakh)',
    'km': 'Camdodia (Khmer)',
    'ki': 'Kenya (Kikuyu/Gikuyu)',
    'rw': 'Rwanda (Kinyarwanda)',
    'ky': 'Kyrgyzstan (Kyrgyz)',
    'kv': 'Russia (Komi)',
    'kg': 'Kongo (Kongo)',
    'ko': 'Korea (Korean)',
    'ku': 'Iraq (Kurdish)',
    'kj': 'Angola (Kwanyama)',
    'la': 'Vatican City (Latin)',
    'lb': 'Luxembourg (Luxembourgish)',
    'lg': 'Uganda (Luganda)',
    'li': 'Netherlands (Limburgish)',
    'ln': 'Congo (Lingala)',
    'lo': 'Laos (Lao)',
    'lt': 'Lithuania (Lithuanian)',
    'lu': 'Congo (Luba-Katanga)',
    'lv': 'Latvia (Latvian)',
    'gv': 'UK (Manx)',
    'mk': 'Macedonia (Macedonian)',
    'mg': 'Madagascar (Malagasy)',
    'ms': 'Malaysia, Brunei, Singapore, (Malay)',
    'ml': 'India (Malayalam)',
    'mt': 'Malta (Maltese)',
    'mi': 'New Zealand (Māori)',
    'mr': 'India (Marathi)',
    'mh': 'Marshall Islands (Marshallese)',
    'mn': 'Mongolia (Mongolian)',
    'na': 'Nauru (Nauruan)',
    'nv': 'USA (Navajo)',
    'nb': 'Noreway (Norwegian Bokmål)',
    'nd': 'Zimbabwe (North Ndebele)',
    'ne': 'Nepal (Nepali)',
    'ng': 'Namibia (Ndonga)',
    'nn': 'Norway (Norwegian Nynorsk)',
    'no': 'Norway (Norwegian)',
    'ii': 'China (Nuosu)',
    'nr': 'South Africa (South Ndebele)',
    'oc': 'Spain (Occitan)',
    'oj': 'Canada (Ojibwa)',
    'cu': 'Slavic (Old Church Slavonic)',
    'om': 'Ethiopia, Kenya (Oromo)',
    'or': 'India (Oriya)',
    'os': 'North Caucasus (Ossetian)',
    'pa': 'India (Punjabi)',
    'pi': 'India (Pāli)',
    'fa': 'Iran (Persian)',
    'pl': 'Poland (Polish)',
    'ps': 'Pashto: Pushto',
    'pt': 'Portugal (Portuguese)',
    'qu': 'Argentina, Bolivia, Colombia, Ecuador, Peru, Chile (Quechua)',
    'rm': 'Switzerland (Romansh)',
    'rn': 'Burundi (Kirundi)',
    'ro': 'Romania (Romanian: Moldavan)',
    'ru': 'Russia (Russian)',
    'sa': 'India (Sanskrit)',
    'sc': 'Italy (Sardinian)',
    'sd': 'India (Sindhi)',
    'se': 'Norway, Sweden, Finland (Northern Sami)',
    'sm': 'Samoa (Samoan)',
    'sg': 'Central African Republic (Sango)',
    'sr': 'Serbia (Serbian)',
    'gd': 'Scotland (Scottish Gaelic)',
    'sn': 'Zimbabwe (Shona)',
    'si': 'Sri Lanka (Sinhala)',
    'sk': 'Croatia, Czech Republic, Slovakia (Slovak)',
    'sl': 'Slovenia (Slovene)',
    'so': 'Somalia (Somali)',
    'st': 'Lesotho (Southern Sotho)',
    'es': 'Spain (Spanish)',
    'su': 'Java, Indonesia (Sundanese)',
    'sw': 'Tanzania, Uganda, Kenya, Congo (Swahili)',
    'ss': 'Eswatini (Swati)',
    'sv': 'Sweden (Swedish)',
    'ta': 'India, Sri Lanka (Tamil)',
    'te': 'India (Telugu)',
    'tg': 'Tajikistan (Tajik)',
    'th': 'Thailand (Thai)',
    'ti': 'Eritrea (Tigrinya)',
    'bo': 'Tibet (Tibetan)',
    'tk': 'Turkmenistan (Turkmen)',
    'tl': 'Philippines (Tagalog)',
    'tn': 'Botswana (Tswana)',
    'to': 'Tonga (Tonga)',
    'tr': 'Turkey (Turkish)',
    'ts': 'South Africa (Tsonga)',
    'tt': 'Russia (Tatar)',
    'tw': 'Ghana (Twi)',
    'ty': 'Tahiti (Tahitian)',
    'ug': 'China - Xinjiang (Uyghur)',
    'uk': 'Ukraine (Ukrainian)',
    'ur': 'Pakistan (Urdu)',
    'uz': 'Uzbekistan (Uzbek)',
    've': 'South Africa (Venda)',
    'vi': 'Vietnam (Vietnamese)',
    'vo': 'Internatinal (Volapük)',
    'wa': 'Belgium, France (Walloon)',
    'cy': 'Wales (Welsh)',
    'wo': 'Senegal, Gambia (Wolof)',
    'fy': 'Netherlands (Western Frisian)',
    'xh': 'South Africa (Xhosa)',
    'yi': 'Europe (Yiddish)',
    'yo': 'Nigeria,Togo, Ghana (Yoruba)',
    'za': 'China (Zhuang)',
    'zu': 'South Africa (Zulu)'}
